name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_call:
    inputs:
      MT_NAME:
        description: 'MT Name'
        required: true
        type: string
        
      MT_FOLDER:
        type: string
        description: 'MT Folder location'
        required: true

      MT_FOLDER_VAR:
        type: string
        description: 'MT Folder location'
        required: true

      environment:
        type: string
        required: true

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "${{ inputs.MT_NAME }}"
      - run: echo "${{ inputs.MT_FOLDER }}"
      - run: echo "${{ vars[input.MT_FOLDER_VAR] }}"
